on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get podman
      run: |
        sudo apt update
        sudo apt install -y podman 
    - name: Compile PyTorch for ARM
      run: |
        podman pull --arch arm64 docker.io/m4gh3/aarch64-linux-gnu-gcc-builder
        podman image ls
        podman run --arch arm64 -v $(pwd):/root docker.io/m4gh3/aarch64-linux-gnu-gcc-builder /usr/bin/qemu-aarch64-static sh -c "
        apt update
        apt install -y python-is-python3 python3-pip git cmake ninja-build
        cd /root
        git clone --depth 1 -j 16 --recursive
        https://github.com/pytorch/pytorch.git -b v2.0.1 
        pip3 install -r pytorch/requirements.txt
        mkdir pytorch_build
        mkdir pytorch_install
        cd pytorch_build
        cmake \
        -DCMAKE_TOOLCHAIN_FILE=../cmake_toolchain.cmake \
        -DUSE_MKLDNN=ON \
        -DBUILD_CUSTOM_PROTOBUF=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DUSE_FFMPEG=ON \
        -DUSE_GFLAGS=ON \
        -DUSE_GLOG=ON \
        -DBUILD_BINARY=ON \
        -DBUILD_PYTHON=OFF \
        -DBUILD_TEST=OFF \
        -DUSE_OPENCV=ON \
        -DUSE_SYSTEM_NCCL=ON \
        -DUSE_DISTRIBUTED=ON \
        -DUSE_CUDA=OFF \
        -DUSE_CUDNN=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=../pytorch_install \
        -GNinja \
        ../pytorch
        ninja install -j 16 "
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: pytorch
        path: ../pytorch_install
