on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu \
        g++-aarch64-linux-gnu python3 python3-pip \
        cmake ninja-build git

    - name: Get PyTorch
      run: |
        git clone --depth 1 -j 16 --recursive \
        https://github.com/pytorch/pytorch.git -b v2.0.1

    - name: Get dependencies
      run: |
        pip3 install -r pytorch/requirements.txt

        #- name: Compile PyTorch for Native
        #  run: |
        #    mkdir pytorch_native_build
        #    mkdir pytorch_native_install
        #    cd pytorch_native_build
        #    cmake \
        #    -DUSE_MKLDNN=ON \
        #    -DBUILD_CUSTOM_PROTOBUF=OFF \
        #    -DBUILD_SHARED_LIBS=ON \
        #    -DUSE_FFMPEG=ON \
        #    -DUSE_GFLAGS=ON \
        #    -DUSE_GLOG=ON \
        #    -DBUILD_BINARY=ON \
        #    -DBUILD_PYTHON=OFF \
        #    -DBUILD_TEST=OFF \
        #    -DUSE_OPENCV=ON \
        #    -DUSE_SYSTEM_NCCL=ON \
        #    -DUSE_DISTRIBUTED=ON \
        #    -DUSE_CUDA=OFF \
        #    -DUSE_CUDNN=OFF \
        #    -DBUILD_SHARED_LIBS=ON \
        #    -DCMAKE_BUILD_TYPE=Release \
        #    -DCMAKE_INSTALL_PREFIX=../pytorch_native_install \
        #    -GNinja \
        #    ../pytorch
        #    ninja install -j 16
        #    cd ..
        #    export PATH=$PATH:$PWD/pytorch_native_install
    - name: Compile PyTorch for ARM
      run: |
        mkdir pytorch_build
        mkdir pytorch_install
        cd pytorch_build
        cmake \
        -DCMAKE_TOOLCHAIN_FILE=../cmake_toolchain.cmake \
        -DUSE_MKLDNN=ON \
        -DBUILD_CUSTOM_PROTOBUF=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DUSE_FFMPEG=ON \
        -DUSE_GFLAGS=ON \
        -DUSE_GLOG=ON \
        -DBUILD_BINARY=ON \
        -DBUILD_PYTHON=OFF \
        -DBUILD_TEST=OFF \
        -DUSE_OPENCV=ON \
        -DUSE_SYSTEM_NCCL=ON \
        -DUSE_DISTRIBUTED=ON \
        -DUSE_CUDA=OFF \
        -DUSE_CUDNN=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=../pytorch_install \
        -GNinja \
        ../pytorch
        ninja build -j 16
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: pytorch
        path: ../pytorch_install
